In [10]:
import numpy as np

t1 = np.arange(1, 5).reshape((2, 2))
t2 = np.arange(6, 10).reshape((2, 2))

print(t1*t2)
print(np.dot(t1,t2))
print(np.matmul(t1,t2))

[[ 6 14]
 [24 36]]
[[22 25]
 [50 57]]
[[22 25]
 [50 57]]
