In [20]:
import numpy as np

X = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]]) # 5 x 4

b = np.zeros([10])
w = np.ones([4,10])
a = X[0]



print(X,w,b)

# X = np.c_(np.ones([5,1]), X)
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.ones(3)
c = np.array([[1,2,3,1],[4,5,6,1],[7,8,9,1]])
np.c_[np.ones([5,1]), X]

# print(X,w,b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]] [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([[ 1.,  1.,  2.,  3.,  4.],
       [ 1.,  5.,  6.,  7.,  8.],
       [ 1.,  9., 10., 11., 12.],
       [ 1., 13., 14., 15., 16.],
       [ 1., 17., 18., 19., 20.]])

In [20]:
import numpy as np

results = {}
results[(1,2)] = (12,13)
results[(3,4)] = (5,6)
for lr, reg in sorted(results):
    train_accuracy, val_accuracy = results[(lr, reg)]
    print('lr %e reg %e train accuracy: %d val accuracy: %d' % (
                lr, reg, train_accuracy, val_accuracy))

lr 1.000000e+00 reg 2.000000e+00 train accuracy: 12 val accuracy: 13
lr 3.000000e+00 reg 4.000000e+00 train accuracy: 5 val accuracy: 6
